version: "3.8"

services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=discount'
    ports:
      - '27017:27017'
    hostname: mongodb
  app:
    depends_on:
      - mongodb
    build: ./
    ports:
      - '8080:8080'
    volumes:
      - .m2:/root/.m2
    hostname: app